import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const root=new URL('../dist/',import.meta.url);
const files=['/','/index.html','/manifest.webmanifest','/icon.svg','/icons/icon-192.png','/icons/icon-512.png','/icons/maskable-512.png'];
for(const name of await readdir(new URL('assets/',root))) if(/\.(js|css)$/.test(name))files.push('/assets/'+name);
const hash=createHash('sha256');
hash.update(await readFile(new URL(import.meta.url)));
for(const file of files.filter(f=>f!=='/'))hash.update(await readFile(new URL(file.slice(1),root)));
const version=hash.digest('hex').slice(0,16);
await writeFile(new URL('sw.js',root),`const CACHE='lamastore-static-${version}';
const FILES=${JSON.stringify(files)};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('lamastore-static-')&&k!==CACHE).map(k=>caches.delete(k))))));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin||url.search||!FILES.includes(url.pathname))return;
 event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(event.request,{ignoreVary:true}))||fetch(event.request)));
});
`);
console.log('Generated static-only service worker',version);
