<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { listJobs,mapJob,visibleJobs } from '../api/processes';
import type { Card } from '../types/api';
const emit=defineEmits<{open:[id:number]}>();
const cards=ref<Card[]>([]),query=ref(''),active=ref(true),busy=ref(false),error=ref(''),total=ref(0);
const jobs=computed(()=>visibleJobs(cards.value,query.value,active.value).map(mapJob));
async function load(more=false){if(busy.value)return;busy.value=true;error.value='';try{const result=await listJobs(more?cards.value.length:0);cards.value=more?[...cards.value,...result.data]:result.data;total.value=result.meta?.total??cards.value.length;}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
onMounted(()=>load());
</script>
<template><div class="page-title"><div><p class="eyebrow">Your maintenance workspace</p><h1>My jobs<span class="count">{{ jobs.length }}</span></h1></div><button class="icon-button" aria-label="Refresh jobs" :disabled="busy" @click="load()">↻</button></div><p class="muted">Jobs available to your openMAINT account.</p><label><span class="sr-only">Search loaded jobs</span><input v-model="query" class="search" type="search" placeholder="Find a job, asset, or location"></label><div class="filter-row"><button :class="['chip',{selected:active}]" @click="active=true">Active</button><button :class="['chip',{selected:!active}]" @click="active=false">All authorized</button></div><p v-if="cards.length<total" class="hint">{{ cards.length }} of {{ total }} jobs loaded. Search applies to loaded jobs.</p>
<p v-if="error" class="error" role="alert">{{ error }} <button class="text-button" @click="load()">Retry</button></p><div v-if="busy&&!cards.length" class="skeleton" role="status">Loading your jobs…</div><div v-else-if="!jobs.length" class="empty panel"><h2>No jobs to show</h2><p>{{ query?'Try another search.':'You’re up to date, or no matching jobs are visible to this account.' }}</p></div>
<div class="jobs"><button v-for="job in jobs" :key="job.id" class="job-card" @click="emit('open',job.id)"><div class="section-heading"><span class="job-number">{{ job.number }}</span><span class="priority" :class="{high:job.priority==='High'}">{{ job.priority || 'No priority' }}</span></div><h2>{{ job.subject }}</h2><p class="equipment">{{ job.equipment || 'Equipment not specified' }}</p><p class="location">{{ job.location || 'Location not specified' }}</p><div class="card-footer"><span class="badge">{{ job.status }}</span><span class="muted">{{ job.team }}</span><span aria-hidden="true">→</span></div></button></div><button v-if="cards.length<total" class="secondary wide" :disabled="busy" @click="load(true)">{{ busy?'Loading…':'Load more jobs' }}</button></template>
