<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { accountingEnabled,listAccounting,recordLabour,type LabourDraft } from '../api/accounting';
import { listWarehouse } from '../api/warehouse';
import { api,ApiError } from '../api/client';
import { translateError } from '../i18n/errors';
import type { Card } from '../types/api';
const {t}=useI18n();
const props=defineProps<{id:number;canEdit:boolean}>();
const labour=ref<Card[]>([]),warehouse=ref<Card[]>([]),enabled=ref(false),loading=ref(true),busy=ref(false),uncertain=ref(false),error=ref(''),warehouseError=ref(''),notice=ref('');
const draft=reactive<LabourDraft>({description:'',date:new Date().toLocaleDateString('en-CA'),hours:0.5,unitPrice:NaN,notes:''});
async function load(){error.value='';try{labour.value=await listAccounting(props.id);const klass=await api.data<{_can_create:boolean}>('classes/LabourAccMov');enabled.value=props.canEdit&&klass._can_create&&await accountingEnabled(props.id);}catch(e){error.value=translateError((e as Error).message);}try{warehouse.value=await listWarehouse(props.id);}catch(e){warehouseError.value=translateError((e as Error).message);}loading.value=false;}
onMounted(load);
async function save(){if(busy.value||uncertain.value)return;busy.value=true;error.value='';try{await recordLabour(props.id,draft);draft.description='';notice.value=t('resources.savedNotice');await load();}catch(e){error.value=translateError((e as Error).message);uncertain.value=e instanceof ApiError&&e.uncertain;}finally{busy.value=false;}}
</script>
<template><section class="panel"><p class="eyebrow">{{ $t('resources.eyebrow') }}</p><h2>{{ $t('resources.title') }}</h2><p v-if="loading" role="status">{{ $t('resources.loading') }}</p><p v-else-if="!labour.length" class="empty">{{ $t('resources.empty') }}</p><article v-for="row in labour" :key="row._id" class="resource-card"><strong>{{ row.Description }}</strong><p>{{ row.Date }} · {{ row.Quantity }} {{ row._type==='LabourAccMov'?$t('resources.unitHours'):$t('resources.unitUnits') }} · {{ row._State_description }}</p></article><small v-if="labour.length===100">{{ $t('resources.showingFirst100') }}</small>
<form v-if="enabled" @submit.prevent="save"><fieldset :disabled="busy||uncertain"><legend class="sr-only">Record labour</legend><label>{{ $t('resources.workPerformed') }}<input v-model="draft.description" required></label><label>{{ $t('resources.workDate') }}<input v-model="draft.date" type="date" required></label><div class="field-pair"><label>{{ $t('resources.hours') }}<input v-model.number="draft.hours" type="number" min="0.01" max="24" step="0.01" required></label><label>{{ $t('resources.hourlyRate') }}<input v-model.number="draft.unitPrice" type="number" min="0" step="0.01" :placeholder="$t('resources.ratePlaceholder')" required></label></div><small>{{ $t('resources.rateHint') }}</small><label>{{ $t('resources.labourNotes') }}<textarea v-model="draft.notes" rows="2"></textarea></label><button class="primary wide">{{ busy?$t('resources.recording'):$t('resources.recordLabour') }}</button></fieldset></form><p v-else-if="!loading" class="hint">{{ $t('resources.labourDisabledHint') }}</p><p v-if="notice" class="success" role="status">{{ notice }}</p><p v-if="error" class="error" role="alert">{{ error }}</p></section>
<section class="panel"><h2>{{ $t('resources.spareParts') }}</h2><p v-if="!warehouse.length" class="empty">{{ $t('resources.noWarehouse') }}</p><article v-for="row in warehouse" :key="row._id" class="resource-card"><strong>{{ row.Description || row._id }}</strong><p>{{ row.Date }} · {{ row._SrcSite_description }}</p></article><p class="hint">{{ $t('resources.sparePartsHint') }}</p><p v-if="warehouseError" class="error" role="alert">{{ warehouseError }}</p></section></template>
