<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { accountingEnabled,listAccounting,recordLabour,type LabourDraft } from '../api/accounting';
import { listWarehouse } from '../api/warehouse';
import { api,ApiError } from '../api/client';
import type { Card } from '../types/api';
const props=defineProps<{id:number;canEdit:boolean}>();
const labour=ref<Card[]>([]),warehouse=ref<Card[]>([]),enabled=ref(false),loading=ref(true),busy=ref(false),uncertain=ref(false),error=ref(''),warehouseError=ref(''),notice=ref('');
const draft=reactive<LabourDraft>({description:'',date:new Date().toLocaleDateString('en-CA'),hours:0.5,unitPrice:NaN,notes:''});
async function load(){error.value='';try{labour.value=await listAccounting(props.id);const klass=await api.data<{_can_create:boolean}>('classes/LabourAccMov');enabled.value=props.canEdit&&klass._can_create&&await accountingEnabled(props.id);}catch(e){error.value=(e as Error).message;}try{warehouse.value=await listWarehouse(props.id);}catch(e){warehouseError.value=(e as Error).message;}loading.value=false;}
onMounted(load);
async function save(){if(busy.value||uncertain.value)return;busy.value=true;error.value='';try{await recordLabour(props.id,draft);draft.description='';notice.value='Labour saved to openMAINT.';await load();}catch(e){error.value=(e as Error).message;uncertain.value=e instanceof ApiError&&e.uncertain;}finally{busy.value=false;}}
</script>
<template><section class="panel"><p class="eyebrow">Resources</p><h2>Time & labour</h2><p v-if="loading" role="status">Loading resources…</p><p v-else-if="!labour.length" class="empty">No accounting movements recorded.</p><article v-for="row in labour" :key="row._id" class="resource-card"><strong>{{ row.Description }}</strong><p>{{ row.Date }} · {{ row.Quantity }} {{ row._type==='LabourAccMov'?'hours':'units' }} · {{ row._State_description }}</p></article><small v-if="labour.length===100">Showing the first 100 movements.</small>
<form v-if="enabled" @submit.prevent="save"><fieldset :disabled="busy||uncertain"><legend class="sr-only">Record labour</legend><label>Work performed<input v-model="draft.description" required></label><label>Work date<input v-model="draft.date" type="date" required></label><div class="field-pair"><label>Hours<input v-model.number="draft.hours" type="number" min="0.01" max="24" step="0.01" required></label><label>Hourly rate<input v-model.number="draft.unitPrice" type="number" min="0" step="0.01" placeholder="Enter rate" required></label></div><small>Use the agreed rate in your openMAINT accounting currency.</small><label>Labour notes<textarea v-model="draft.notes" rows="2"></textarea></label><button class="primary wide">{{ busy?'Saving…':'Record labour' }}</button></fieldset></form><p v-else-if="!loading" class="hint">Labour entry is not enabled for this activity and account.</p><p v-if="notice" class="success" role="status">{{ notice }}</p><p v-if="error" class="error" role="alert">{{ error }}</p></section>
<section class="panel"><h2>Spare parts</h2><p v-if="!warehouse.length" class="empty">No warehouse movements recorded.</p><article v-for="row in warehouse" :key="row._id" class="resource-card"><strong>{{ row.Description || row._id }}</strong><p>{{ row.Date }} · {{ row._SrcSite_description }}</p></article><p class="hint">Spare-part entry is not available yet. Stock-backed integration still needs validation.</p><p v-if="warehouseError" class="error" role="alert">{{ warehouseError }}</p></section></template>
